/**
 * Pulls the webfonts local, and writes the @font-face rules to match.
 *
 * Run with `npm run fonts`. Both outputs are committed and nothing reads this
 * at build time; it exists so the files can be traced back to a version of a
 * family rather than being six binaries someone dropped in a folder.
 *
 * The site used to link fonts.googleapis.com from <head>. That stylesheet is
 * render-blocking and lives on a third-party origin, so no pixel could be
 * painted until a fresh DNS lookup, TLS handshake and round trip had all
 * finished — 813 ms of the mobile Largest Contentful Paint, to deliver 1.2 kB
 * of CSS. Served from our own origin the connection is already open, and the
 * rules ride along in the stylesheet the page was fetching anyway.
 *
 * Both families are variable, so one file covers a whole weight range and the
 * eighteen rules Google emits collapse to six. Only latin and latin-ext are
 * kept: unicode-range means a browser never downloads a subset it has no
 * characters for, so the Cyrillic and Vietnamese cuts cost nothing at runtime
 * — they were simply dead weight in the repository.
 *
 * DM Sans and Plus Jakarta Sans are both under the SIL Open Font License,
 * which is what makes hosting them ourselves allowed. See public/fonts/OFL.txt.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const API = 'https://fonts.googleapis.com/css2'
const QUERY =
  'family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400' +
  '&family=Plus+Jakarta+Sans:wght@700;800&display=swap'

/** Google serves woff2 and variable cuts only to a browser it recognises. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const KEEP = new Set(['latin', 'latin-ext'])
const FONT_DIR = 'public/fonts'
const CSS_OUT = 'src/assets/styles/fonts.css'

/** Weight ranges the variable files actually cover, for the collapsed rules. */
const RANGES = {
  'DM Sans': '400 700',
  'Plus Jakarta Sans': '700 800',
}

function slug(family, style, subset) {
  const base = family.toLowerCase().replaceAll(' ', '-')
  return `${base}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`
}

async function main() {
  const res = await fetch(`${API}?${QUERY}`, { headers: { 'User-Agent': UA } })
  if (!res.ok) {
    throw new Error(`google fonts returned ${res.status}`)
  }
  const css = await res.text()

  const faces = new Map()
  for (const [, subset, body] of css.matchAll(/\/\* (\S+) \*\/\s*@font-face \{(.*?)\}/gs)) {
    if (!KEEP.has(subset)) {
      continue
    }
    const family = /font-family: '([^']+)'/.exec(body)[1]
    const style = /font-style: (\w+)/.exec(body)[1]
    const url = /url\(([^)]+)\)/.exec(body)[1]
    const range = /unicode-range: ([^;]+);/.exec(body)[1]
    // Keyed by file: the same variable cut is repeated once per weight asked for.
    faces.set(url, { family, style, subset, range, file: slug(family, style, subset) })
  }

  await mkdir(FONT_DIR, { recursive: true })

  const rules = []
  for (const [url, face] of faces) {
    const font = await fetch(url)
    if (!font.ok) {
      throw new Error(`${face.file}: ${font.status}`)
    }
    const bytes = Buffer.from(await font.arrayBuffer())
    await writeFile(path.join(FONT_DIR, face.file), bytes)
    console.log(`${face.file.padEnd(36)} ${String(Math.round(bytes.length / 1024)).padStart(3)} KB`)

    rules.push(
      [
        '@font-face {',
        `  font-family: '${face.family}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${RANGES[face.family]};`,
        // Text in a fallback face beats no text at all, and the swap is what
        // keeps a slow font off the critical path for first paint.
        '  font-display: swap;',
        `  src: url('/fonts/${face.file}') format('woff2');`,
        `  unicode-range: ${face.range};`,
        '}',
      ].join('\n'),
    )
  }

  const header = [
    '/*',
    ' * Generated by scripts/fonts.mjs (npm run fonts). Do not edit.',
    ' *',
    ' * Self-hosted so that first paint does not wait on a third-party origin.',
    ' * The files these point at live in public/fonts and are served unhashed, so',
    ' * the preload in index.html can name one and stay correct across builds.',
    ' */',
    '',
  ].join('\n')

  await writeFile(CSS_OUT, `${header}${rules.join('\n\n')}\n`)
  console.log(`\n${faces.size} faces -> ${CSS_OUT}`)
}

main()
