/**
 * Writes the mark in public/favicon.svg.
 *
 * Run `npm run logo:mark`. The SVG is the committed artefact and nothing reads
 * this at build time; it exists so the outlines stay editable, since each blade
 * is a sampled offset curve rather than something anyone can type.
 *
 * Five blades out of one tuft, spreading as they rise the way a fountain
 * spreads. Drawing a whole lawn was the mistake this replaces: at a glance, and
 * on a shirt, forty blades are a green texture rather than a mark. Five have a
 * silhouette you can recognise across a room.
 *
 * Three things this went through before it worked:
 *
 * - Roots meeting at a point make a succulent. They sit along a short baseline
 *   here, because grass comes out of a tuft.
 * - Blades that carry on out to the horizontal look like a spider plant dying.
 *   Every tip finishes pointing up and out, none past about sixty degrees.
 * - Straight blades are a starburst. Each one leaves the tuft vertical and only
 *   turns outwards near the top, which is the whole difference.
 *
 * Each blade is a quadratic centreline offset either side by a width profile
 * that holds most of the width up the shaft and closes only near the tip. A
 * plain taper spends all its width at the root, where the blades overlap
 * anyway, and leaves a hair everywhere you actually look.
 */

import { writeFileSync } from 'node:fs'

const SIZE = 64

/** Where the tuft sits. Low enough to leave the blades room to arc over. */
const ROOT_Y = 50

/** Points sampled along each edge. Enough to look smooth at the sizes we use. */
const STEPS = 18

const SKY = '#96cfa1'
const SOIL = '#7c4720'

/**
 * Back to front: the outer pair is laid down first so the inner blades cross
 * in front of them, which is what gives the fan a front and a back.
 *
 * `ctrl` sits well above the root and close to it in x. That is what makes the
 * blade leave the tuft going up and only turn outwards near the top; pull it
 * sideways and the blade leans out of the ground instead of arching.
 */
const BLADES = [
  { root: 27.5, tip: [9, 19], ctrl: [25.5, 28], hw: 1.5, fill: '#0d6520' },
  { root: 36.5, tip: [55, 17], ctrl: [38.5, 27], hw: 1.5, fill: '#0d6520' },
  { root: 29.5, tip: [19, 8], ctrl: [29.5, 24], hw: 1.7, fill: '#17801f' },
  { root: 34.5, tip: [45.5, 6.5], ctrl: [34.5, 23], hw: 1.7, fill: '#17801f' },
  { root: 32, tip: [32.5, 4], ctrl: [31.5, 22], hw: 1.85, fill: '#23922a' },
]

const round = n => Number(n.toFixed(1))

function pointAt(p0, p1, p2, t) {
  const u = 1 - t
  return [
    u * u * p0[0] + 2 * u * t * p1[0] + t * t * p2[0],
    u * u * p0[1] + 2 * u * t * p1[1] + t * t * p2[1],
  ]
}

function tangentAt(p0, p1, p2, t) {
  const x = 2 * (1 - t) * (p1[0] - p0[0]) + 2 * t * (p2[0] - p1[0])
  const y = 2 * (1 - t) * (p1[1] - p0[1]) + 2 * t * (p2[1] - p1[1])
  const length = Math.hypot(x, y) || 1
  return [x / length, y / length]
}

/** Full at the root, still nine tenths at mid height, closed at the tip. */
function widthAt(hw, t) {
  return hw * Math.pow(1 - Math.pow(t, 2.4), 0.55)
}

function outline({ root, tip, ctrl, hw }) {
  const base = [root, ROOT_Y]
  const left = []
  const right = []

  for (let i = 0; i <= STEPS; i++) {
    // Samples bunched towards the tip. Spaced evenly, the last step spans the
    // whole of the taper and the point comes out as a blunt cut instead.
    const t = 1 - Math.pow(1 - i / STEPS, 1.7)
    const [x, y] = pointAt(base, ctrl, tip, t)
    const [tx, ty] = tangentAt(base, ctrl, tip, t)
    const w = widthAt(hw, t)
    left.push([x + ty * w, y - tx * w])
    right.push([x - ty * w, y + tx * w])
  }

  // Up one edge and back down the other. The tips coincide, so one is dropped.
  return [...left, ...right.reverse().slice(1)]
    .map(([x, y]) => `${round(x)} ${round(y)}`)
    .join('L')
}

/** The tuft, as paths in the 64-unit space the blades are defined in. */
const tuft = indent =>
  BLADES.map(b => `${indent}<path d="M${outline(b)}Z" fill="${b.fill}"/>`).join('\n')

/**
 * A mound, not a horizon: the tuft grows out of it rather than stands on it.
 * The crest has to stay above the roots or their cut ends show.
 */
const mound = (w, h, edge, crest) =>
  `M0 ${h}L0 ${edge}` +
  `C${round(w * 0.17)} ${edge} ${round(w * 0.3)} ${crest} ${round(w / 2)} ${crest}` +
  `C${round(w * 0.7)} ${crest} ${round(w * 0.83)} ${edge} ${w} ${edge}` +
  `L${w} ${h}Z`

const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}">
  <title>Plan a Lawn</title>
  <!--
    Five blades out of one tuft. Generated by scripts/logo-mark.mjs — edit
    there, not here, and the reasoning behind the shapes lives in that file.

    Deliberately square. The header and the home page round it in CSS, and the
    tab and home screen apply their own masks, so a radius baked in here would
    only fight them.
  -->
  <rect width="${SIZE}" height="${SIZE}" fill="${SKY}"/>
${tuft('  ')}
  <path d="M0 ${SIZE}L0 54.5C11 54.5 19 48.5 32 48.5C45 48.5 53 54.5 ${SIZE} 54.5L${SIZE} ${SIZE}Z" fill="${SOIL}"/>
</svg>
`

/**
 * The social card: the same scene, given room to breathe.
 *
 * A preview card is 1200x630 and the mark is square, so it cannot simply be
 * scaled up — one tuft alone leaves the sides empty. Two smaller tufts set
 * further down the mound fill the width and read as distance rather than as
 * clutter, and the soil runs the full width to hold the whole thing together.
 *
 * This one is written next to this script rather than into public/, because
 * nothing fetches it. It is only the source scripts/logo-icons.py rasterises
 * into the og-image.jpg that crawlers actually read.
 */
const CARD = { w: 1200, h: 630, edge: 575, crest: 522 }

/** Root y in card space, then the transform that puts a tuft's roots there. */
const place = (x, rootY, scale) =>
  `translate(${round(x - 32 * scale)} ${round(rootY - ROOT_Y * scale)}) scale(${scale})`

const TUFTS = [
  { x: 250, rootY: 566, scale: 6.4 },
  { x: 950, rootY: 570, scale: 6.8 },
  { x: 600, rootY: 536, scale: 10.2 },
]

const card = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${CARD.w} ${CARD.h}">
  <title>Plan a Lawn</title>
  <!-- Generated by scripts/logo-mark.mjs. Source for public/og-image.jpg. -->
  <rect width="${CARD.w}" height="${CARD.h}" fill="${SKY}"/>
${TUFTS.map(t => `  <g transform="${place(t.x, t.rootY, t.scale)}">\n${tuft('    ')}\n  </g>`).join('\n')}
  <path d="${mound(CARD.w, CARD.h, CARD.edge, CARD.crest)}" fill="${SOIL}"/>
</svg>
`

for (const [path, body] of [
  ['public/favicon.svg', icon],
  ['scripts/og-card.svg', card],
]) {
  writeFileSync(new URL(`../${path}`, import.meta.url), body)
  console.log(`${path.padEnd(20)} ${body.length} bytes`)
}
