// Font Awesome – free icons, plus the lawn-specific ones drawn in icons/lawn.ts.
// Import this file in main.ts to register the library and icons.

import { library } from '@fortawesome/fontawesome-svg-core'
import { lawnIcons } from './icons/lawn'

import {
  faArrowRight,
  faArrowUpRightFromSquare,
  faBars,
  faBug,
  faBugSlash,
  faCalendarDay,
  faChartBar,
  faCheck,
  faChevronDown,
  faClock,
  faCloud,
  faCloudSun,
  faCodeCompare,
  faDroplet,
  faFileLines,
  faFlask,
  faFloppyDisk,
  faGrip,
  faLayerGroup,
  faLeaf,
  faListCheck,
  faLocationCrosshairs,
  faLocationDot,
  faPenToSquare,
  faRuler,
  faScaleBalanced,
  faShieldHalved,
  faShower,
  faSnowflake,
  faSprayCan,
  faSun,
  faTable,
  faTemperatureHalf,
  faTree,
  faTriangleExclamation,
  faTrowel,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faArrowRight,
  faArrowUpRightFromSquare,
  faBars,
  faBug,
  faBugSlash,
  faCalendarDay,
  faChartBar,
  faCheck,
  faChevronDown,
  faClock,
  faCloud,
  faCloudSun,
  faCodeCompare,
  faDroplet,
  faFileLines,
  faFlask,
  faFloppyDisk,
  faGrip,
  faLayerGroup,
  faLeaf,
  faListCheck,
  faLocationCrosshairs,
  faLocationDot,
  faPenToSquare,
  faRuler,
  faScaleBalanced,
  faShieldHalved,
  faShower,
  faSnowflake,
  faSprayCan,
  faSun,
  faTable,
  faTemperatureHalf,
  faTree,
  faTriangleExclamation,
  faTrowel,
  faXmark,
  ...lawnIcons,
)
